name: new_event
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_plugin_android_lifecycle: ^2.0.2
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  crypto: ^3.0.0
  intl: any
  animated_background: ^2.0.0
  appwrite: ^14.0.0
  flutter_secure_storage: ^9.0.0  # Optional for secure storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Ensure it matches SDK version

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Untitleddesign.png
