name: new_event
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_plugin_android_lifecycle: ^2.0.2
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  crypto: ^3.0.0
  intl: any
  animated_background: ^2.0.0
  appwrite: ^14.0.0
  flutter_secure_storage: ^9.0.0  # Optional for secure storage
  carousel_slider: ^5.0.0
  flip_card: ^0.7.0
  flutter_card_swiper: ^6.0.0  # Adjust version if needed
  google_fonts: ^6.1.0
  multi_date_picker: ^0.0.1-beta.1
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Ensure it matches SDK version

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Untitleddesign.png
    - assets/Black and White Metallic Tech Talk Event Poster.jpeg
    - assets/Cartel De Inteligencia Artificial Azul _ Plantilla PSD Descarga Gratuita - Pikbest.jpeg
    - assets/College.jpeg
    - assets/download (1).jpeg
    - assets/download.jpeg
    - assets/Free Vector _ Gaming design template.jpeg
    - assets/Futuristic Educational Technology Exhibition Poster.jpeg
    - assets/Premium Vector _ Flat prom vertical flyer template.jpeg
    - assets/Technology Flyer Template.jpeg
    - assets/robot_poster.jpeg
    - assets/Tech Seminar Corporate Flyer Template.jpeg
    - assets/stool.jpg


